apiVersion: v1
kind: Pod
metadata:
  name: tacos-cloud-v2
  namespace: default
  labels:
    name: tacos-cloud-v2
spec:
  containers:
    - image: haozhenwu/tacos-cloud-v2:latest
      name: tacos-cloud-v2
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP